name: Publish to Docker
on:
  push:
    branches:
      - 'master'
env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/tekster-rs:${{ github.sha }}
jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Build and publish Docker image
        env:
          NAME: tekster
          GITHUB_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
        run: |
          docker build -t ${IMAGE} .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE}
